blank_issues_enabled: true
contact_links:
    - name: ğŸ•® Documentation
      url: https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages
      about: "For documentation use the wiki tab"
    - name: ğŸŒ About
      url: https://zank.it
      about: "About the creator of this repository"
